### ISSUE TITLE
Deprecate AttributeTypeBehavior

### ISSUE THREAD

**Issue by serieznyi** [consultnn/yii2-behaviors#1]
Я начинаю сомневаться в целесообразности использования AttributeTypeBehavior.
Просто все те же операции можно сделать и с помощью обычных правил Yii2.
Например: 

1) Приведение к простому типу 
`["status", "filter" => function($value){return (int) $value;}]`

2) Приведение к MongoId
`["user_id", "filter" => function($value){return \MongoId($value);}]`

3) Приведение к массиву MongoId

```
[
"rubric_ids",
    "filter" => function($ids){
        return array_map(
            function($id){return \MongoId($id);},
            $ids
        );
    }
]
```

Единственный плюс, который я вижу в этом поведении - приведение к нужному типу по правилам валидации полей. Но я не уверен, что ради этого стоит его использовать. 
Что вы думаете?

**Comment by batyrmastyr** [comment]
С одной стороны - да, фильтр дешевле по накладным расходам, но тут мы автомагически приводим числовые и булевы атрибуты к нужному типу и частично избавляемся от дублирования в правилах.
В случае с MongoId и массивами имеем недоделанность поведения:  
http://www.yiiframework.com/doc-2.0/yii-mongodb-validators-mongoidvalidator.html
http://www.yiiframework.com/doc-2.0/yii-validators-eachvalidator.html 
Обрабатывая эти два в parseValidators можно было бы просто подключать поведение и ничего не настраивать.
Ну и в случае с монгой - грядущий переход на mongodb проще учесть один раз в поведении, чем устраивать массовую замену по всему коду

**Comment by serieznyi** [comment]
@sokrat @batyrmastyr 

Тогда предлагаю отказаться от маппинга стандартных типов.
Пусть поведение без параметров использует валидаторы из правил для приведения стандартных типов.

А для приведения пользовательских типов можно позволить 
использовать анонимные функции для преобразований.

```
[
             'class' => AttributeTypeBehavior::class,
                'attributes' => [
                 'user_attribute'  => function($value) {
                      return 'Bla-bla value';
                 },
             ]
]
```

**Comment by batyrmastyr** [comment]
Поддерживаю.

**Comment by sokrat** [comment]
Да там весь экстеншн переписывать надо!

**Comment by serieznyi** [comment]
Тогда нужно начать с того, что бы залочить этот пакет во всех проектах на конкретной версии.

**Comment by serieznyi** [comment]
@sokrat @batyrmastyr
А как поступить с новой версией mongodb. Я вот сейчас использую уже ее и там как минимум ObjectID вместо MongoID. Делать совместимость или пилить в отдельной ветке ?

**Comment by batyrmastyr** [comment]
Я за ветку 2.0 с требованием ext-mongodb (если композер уже поддерживает) или php7.

**Comment by serieznyi** [comment]
@batyrmastyr 

composer поддерживает

**Comment by serieznyi** [comment]
В общем я начал по чуть-чуть приводить репозиторий в порядок(#2), так что текущий issue считаю не актуальным.
