### ISSUE TITLE
New major version

### ISSUE THREAD

**Issue by serieznyi** [consultnn/yii2-behaviors#2]
# Common
- [x] Add .github dir with files for contributors
- [ ] Refactor `README.md` . Use some standard format
- [ ] Add tests
- [ ] Add docs
# AttributeTypeBehavior
- [ ] For cast types use standard validators
- [x] Rename `setType` method to `castValue` (conflicts with some of our fields)
- [ ] Add casting user types by anonymous functions
- [ ] Rename all setters
# Before release
- [ ] Change branch in badges
- [ ] Set correct composer alias in composer file

**Comment by batyrmastyr** [comment]
Ещё все прочие set\* переименовать не забудь
